import { PrismaClient,Priority,TaskStatus,ReportStatus } from '@prisma/client';import bcrypt from 'bcryptjs';
const db=new PrismaClient();
const names=[['admin@example.com','Avery Admin','ADMIN'],['manager@example.com','Morgan Manager','MANAGER'],['member1@example.com','John Silva','TEAM_MEMBER'],['member2@example.com','Sarah Chen','TEAM_MEMBER'],['member3@example.com','Alex Perera','TEAM_MEMBER'],['member4@example.com','Michael Reed','TEAM_MEMBER']] as const;
const projects=[['Client Alpha','Customer delivery platform'],['Internal Tooling','Developer productivity'],['R&D','Product experiments'],['Marketing','Growth and content']];
async function main(){
  await db.review.deleteMany();await db.reportVersion.deleteMany();await db.activityLog.deleteMany();await db.report.deleteMany();await db.projectAssignment.deleteMany();await db.project.deleteMany();await db.user.deleteMany();
  const passwordHash=await bcrypt.hash('Password123!',12);const users=[];for(const [email,name,role] of names)users.push(await db.user.create({data:{email,name,role,passwordHash}}));
  const ps:{id:string}[]=[];for(const [name,description] of projects)ps.push(await db.project.create({data:{name,description}})); const manager=users[1];
  await db.projectAssignment.createMany({data:users.slice(2).flatMap((user)=>ps.map((project)=>({userId:user.id,projectId:project.id})))});
  for(let u=2;u<6;u++)for(let w=0;w<4;w++){
    const monday=new Date();monday.setUTCHours(0,0,0,0);monday.setUTCDate(monday.getUTCDate()-((monday.getUTCDay()+6)%7)-w*7);const sunday=new Date(monday);sunday.setUTCDate(sunday.getUTCDate()+6);
    const status:ReportStatus=w===0?(['SUBMITTED','NEEDS_CORRECTION','APPROVED','DRAFT'][u-2] as ReportStatus):w===1?'APPROVED':w===2?'NEEDS_CORRECTION':'APPROVED';
    const report=await db.report.create({data:{userId:users[u].id,projectId:ps[(u+w)%ps.length].id,weekStartDate:monday,weekEndDate:sunday,status,notes:'Focused on reliable delivery and team collaboration.',links:['https://example.com/deliverable'],submittedAt:status==='DRAFT'?null:new Date(),approvedAt:status==='APPROVED'?new Date():null,tasks:{create:[{name:'Implement reporting workflow',priority:Priority.HIGH,plannedPercentage:100,actualPercentage:90-w*5,status:w===0?TaskStatus.IN_PROGRESS:TaskStatus.COMPLETED,plannedTime:16,actualTime:15,deliverable:'Reviewed feature branch'},{name:'Regression testing',priority:Priority.MEDIUM,plannedPercentage:80,actualPercentage:100,status:TaskStatus.COMPLETED,plannedTime:8,actualTime:9,deliverable:'Test results'}]},nextWeekTasks:{create:[{name:'Release improvements',description:'Deploy and monitor the next increment',priority:Priority.HIGH}]},blockers:{create:[{title:'Environment access',description:'Waiting for staging permissions',isKeyIssue:true,status:w>0?'RESOLVED':'OPEN'}]},achievements:{create:[{title:'Milestone delivered',description:'Completed the planned iteration with good test coverage',isKeyAchievement:true}]},workHours:{create:[{workType:'Development',hours:22+u},{workType:'Testing',hours:8},{workType:'Meetings',hours:5}]}}});
    if(status!=='DRAFT'){const full=await db.report.findUnique({where:{id:report.id},include:{tasks:true,nextWeekTasks:true,blockers:true,achievements:true,workHours:true}});const version=await db.reportVersion.create({data:{reportId:report.id,versionNumber:1,snapshot:full!}});if(status==='APPROVED'||status==='NEEDS_CORRECTION')await db.review.create({data:{reportId:report.id,reviewerId:manager.id,versionId:version.id,action:status==='APPROVED'?'APPROVED':'CHANGES_REQUESTED',comment:status==='NEEDS_CORRECTION'?'Please clarify the deliverable and update completion percentages.':'Clear and complete report.'}})}
  }
  await db.activityLog.createMany({data:[{actorId:users[2].id,action:'REPORT_SUBMITTED',description:'John submitted this week’s report'},{actorId:manager.id,action:'APPROVED',description:'Morgan approved Sarah’s report'},{actorId:manager.id,action:'CHANGES_REQUESTED',description:'Morgan requested changes from Alex'}]});console.log('Seeded WeekFlow demo data. Password: Password123!');
}
main().finally(()=>db.$disconnect());
