import express from "express";
import cors from "cors";
import helmet from "helmet";
import { env } from "./config/env.js";
import { authenticate } from "./middleware/auth.js";
import { errorHandler, notFound } from "./middleware/error.js";
import { authRouter } from "./routes/auth.routes.js";
import { reportRouter } from "./routes/report.routes.js";
import { projectRouter } from "./routes/project.routes.js";
import { userRouter } from "./routes/user.routes.js";
import { dashboardRouter } from "./routes/dashboard.routes.js";
import { aiRouter } from "./routes/ai.routes.js";
export const app = express();
app.use(helmet());
app.use(cors({ origin: env.CLIENT_URL }));
app.use(express.json({ limit: "1mb" }));
app.get("/api/health", (_req, res) => res.json({ status: "ok" }));
app.use("/api/auth", authRouter);
app.use("/api/reports", authenticate, reportRouter);
app.use("/api/projects", authenticate, projectRouter);
app.use("/api/users", authenticate, userRouter);
app.use("/api/dashboard", authenticate, dashboardRouter);
app.use("/api/ai", authenticate, aiRouter);
app.use(notFound);
app.use(errorHandler);
