import{beforeEach,describe,expect,it,vi}from'vitest';import request from'supertest';import jwt from'jsonwebtoken';
const mocks=vi.hoisted(()=>({findUnique:vi.fn(),findMany:vi.fn(),count:vi.fn(),transaction:vi.fn()}));
vi.mock('../src/config/prisma.js',()=>({prisma:{report:{findUnique:mocks.findUnique,findMany:mocks.findMany,count:mocks.count},$transaction:mocks.transaction}}));
import{app}from'../src/app.js';
const secret='test-secret-that-is-long-enough';const token=(userId:string,role:string)=>jwt.sign({userId,role},secret);
describe('API authorization',()=>{beforeEach(()=>vi.clearAllMocks());
  it('rejects unauthenticated protected requests',async()=>{expect((await request(app).get('/api/reports/my')).status).toBe(401)});
  it('prevents a member from accessing another member report',async()=>{mocks.findUnique.mockResolvedValue({id:'report-b',userId:'member-b'});const r=await request(app).get('/api/reports/report-b').set('Authorization',`Bearer ${token('member-a','TEAM_MEMBER')}`);expect(r.status).toBe(403)});
  it('allows a manager to access a member report',async()=>{mocks.findUnique.mockResolvedValue({id:'report-b',userId:'member-b',versions:[],reviews:[]});const r=await request(app).get('/api/reports/report-b').set('Authorization',`Bearer ${token('manager','MANAGER')}`);expect(r.status).toBe(200)});
  it('prevents a member from accessing manager report listing',async()=>{const r=await request(app).get('/api/reports').set('Authorization',`Bearer ${token('member-a','TEAM_MEMBER')}`);expect(r.status).toBe(403)});
  it('rejects an invalid submission status transition',async()=>{mocks.findUnique.mockResolvedValue({id:'r1',userId:'member-a',status:'APPROVED',tasks:[],nextWeekTasks:[],blockers:[],achievements:[],workHours:[]});const r=await request(app).post('/api/reports/r1/submit').set('Authorization',`Bearer ${token('member-a','TEAM_MEMBER')}`);expect(r.status).toBe(409)});
});
